# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160301_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=765, null=True, unique=True),
        ),
    ]
