# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diferentes', '0004_auto_20160301_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
