# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diferentes', '0005_auto_20160301_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
