# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diferentes', '0003_auto_20160301_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='state',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
