# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diferentes', '0007_userstatus_last_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='last_download',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
