# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160301_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(),
        ),
    ]
